
package publicadores.PublicadorUsuario;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ControladorPublishUsuario", targetNamespace = "http://Publicadores/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ControladorPublishUsuario {


    /**
     * 
     * @return
     *     returns publicadores.DtUsuarioArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publicadores/ControladorPublishUsuario/retornarUsuariosRequest", output = "http://Publicadores/ControladorPublishUsuario/retornarUsuariosResponse")
    public DtUsuarioArray retornarUsuarios();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Publicadores/ControladorPublishUsuario/returnStringRequest", output = "http://Publicadores/ControladorPublishUsuario/returnStringResponse")
    public String returnString();

}
