
package publicadores;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ControladorPublishRegistroService", targetNamespace = "http://Publicadores/", wsdlLocation = "http://127.0.0.1:1927/controladorRegistro?wsdl")
public class ControladorPublishRegistroService
    extends Service
{

    private final static URL CONTROLADORPUBLISHREGISTROSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONTROLADORPUBLISHREGISTROSERVICE_EXCEPTION;
    private final static QName CONTROLADORPUBLISHREGISTROSERVICE_QNAME = new QName("http://Publicadores/", "ControladorPublishRegistroService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:1927/controladorRegistro?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTROLADORPUBLISHREGISTROSERVICE_WSDL_LOCATION = url;
        CONTROLADORPUBLISHREGISTROSERVICE_EXCEPTION = e;
    }

    public ControladorPublishRegistroService() {
        super(__getWsdlLocation(), CONTROLADORPUBLISHREGISTROSERVICE_QNAME);
    }

    public ControladorPublishRegistroService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTROLADORPUBLISHREGISTROSERVICE_QNAME, features);
    }

    public ControladorPublishRegistroService(URL wsdlLocation) {
        super(wsdlLocation, CONTROLADORPUBLISHREGISTROSERVICE_QNAME);
    }

    public ControladorPublishRegistroService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTROLADORPUBLISHREGISTROSERVICE_QNAME, features);
    }

    public ControladorPublishRegistroService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ControladorPublishRegistroService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ControladorPublishRegistro
     */
    @WebEndpoint(name = "ControladorPublishRegistroPort")
    public ControladorPublishRegistro getControladorPublishRegistroPort() {
        return super.getPort(new QName("http://Publicadores/", "ControladorPublishRegistroPort"), ControladorPublishRegistro.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ControladorPublishRegistro
     */
    @WebEndpoint(name = "ControladorPublishRegistroPort")
    public ControladorPublishRegistro getControladorPublishRegistroPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Publicadores/", "ControladorPublishRegistroPort"), ControladorPublishRegistro.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTROLADORPUBLISHREGISTROSERVICE_EXCEPTION!= null) {
            throw CONTROLADORPUBLISHREGISTROSERVICE_EXCEPTION;
        }
        return CONTROLADORPUBLISHREGISTROSERVICE_WSDL_LOCATION;
    }

}
