
package publicadores;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ControladorPublishInstitucionDeportivaService", targetNamespace = "http://Publicadores/", wsdlLocation = "http://127.0.0.1:1927/controladorInstitucionDeportiva?wsdl")
public class ControladorPublishInstitucionDeportivaService
    extends Service
{

    private final static URL CONTROLADORPUBLISHINSTITUCIONDEPORTIVASERVICE_WSDL_LOCATION;
    private final static WebServiceException CONTROLADORPUBLISHINSTITUCIONDEPORTIVASERVICE_EXCEPTION;
    private final static QName CONTROLADORPUBLISHINSTITUCIONDEPORTIVASERVICE_QNAME = new QName("http://Publicadores/", "ControladorPublishInstitucionDeportivaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:1927/controladorInstitucionDeportiva?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTROLADORPUBLISHINSTITUCIONDEPORTIVASERVICE_WSDL_LOCATION = url;
        CONTROLADORPUBLISHINSTITUCIONDEPORTIVASERVICE_EXCEPTION = e;
    }

    public ControladorPublishInstitucionDeportivaService() {
        super(__getWsdlLocation(), CONTROLADORPUBLISHINSTITUCIONDEPORTIVASERVICE_QNAME);
    }

    public ControladorPublishInstitucionDeportivaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTROLADORPUBLISHINSTITUCIONDEPORTIVASERVICE_QNAME, features);
    }

    public ControladorPublishInstitucionDeportivaService(URL wsdlLocation) {
        super(wsdlLocation, CONTROLADORPUBLISHINSTITUCIONDEPORTIVASERVICE_QNAME);
    }

    public ControladorPublishInstitucionDeportivaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTROLADORPUBLISHINSTITUCIONDEPORTIVASERVICE_QNAME, features);
    }

    public ControladorPublishInstitucionDeportivaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ControladorPublishInstitucionDeportivaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ControladorPublishInstitucionDeportiva
     */
    @WebEndpoint(name = "ControladorPublishInstitucionDeportivaPort")
    public ControladorPublishInstitucionDeportiva getControladorPublishInstitucionDeportivaPort() {
        return super.getPort(new QName("http://Publicadores/", "ControladorPublishInstitucionDeportivaPort"), ControladorPublishInstitucionDeportiva.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ControladorPublishInstitucionDeportiva
     */
    @WebEndpoint(name = "ControladorPublishInstitucionDeportivaPort")
    public ControladorPublishInstitucionDeportiva getControladorPublishInstitucionDeportivaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Publicadores/", "ControladorPublishInstitucionDeportivaPort"), ControladorPublishInstitucionDeportiva.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTROLADORPUBLISHINSTITUCIONDEPORTIVASERVICE_EXCEPTION!= null) {
            throw CONTROLADORPUBLISHINSTITUCIONDEPORTIVASERVICE_EXCEPTION;
        }
        return CONTROLADORPUBLISHINSTITUCIONDEPORTIVASERVICE_WSDL_LOCATION;
    }

}
