
package publicadores;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "RegistroExistenteException", targetNamespace = "http://Publicadores/")
public class RegistroExistenteException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private RegistroExistenteException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public RegistroExistenteException_Exception(String message, RegistroExistenteException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public RegistroExistenteException_Exception(String message, RegistroExistenteException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: publicadores.RegistroExistenteException
     */
    public RegistroExistenteException getFaultInfo() {
        return faultInfo;
    }

}
