
package publicadores.publicadorClase;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ControladorPublishClaseService", targetNamespace = "http://Publicadores/", wsdlLocation = "http://127.0.0.1:1927/controladorClase?wsdl")
public class ControladorPublishClaseService
    extends Service
{

    private final static URL CONTROLADORPUBLISHCLASESERVICE_WSDL_LOCATION;
    private final static WebServiceException CONTROLADORPUBLISHCLASESERVICE_EXCEPTION;
    private final static QName CONTROLADORPUBLISHCLASESERVICE_QNAME = new QName("http://Publicadores/", "ControladorPublishClaseService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:1927/controladorClase?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTROLADORPUBLISHCLASESERVICE_WSDL_LOCATION = url;
        CONTROLADORPUBLISHCLASESERVICE_EXCEPTION = e;
    }

    public ControladorPublishClaseService() {
        super(__getWsdlLocation(), CONTROLADORPUBLISHCLASESERVICE_QNAME);
    }

    public ControladorPublishClaseService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTROLADORPUBLISHCLASESERVICE_QNAME, features);
    }

    public ControladorPublishClaseService(URL wsdlLocation) {
        super(wsdlLocation, CONTROLADORPUBLISHCLASESERVICE_QNAME);
    }

    public ControladorPublishClaseService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTROLADORPUBLISHCLASESERVICE_QNAME, features);
    }

    public ControladorPublishClaseService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ControladorPublishClaseService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ControladorPublishClase
     */
    @WebEndpoint(name = "ControladorPublishClasePort")
    public ControladorPublishClase getControladorPublishClasePort() {
        return super.getPort(new QName("http://Publicadores/", "ControladorPublishClasePort"), ControladorPublishClase.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ControladorPublishClase
     */
    @WebEndpoint(name = "ControladorPublishClasePort")
    public ControladorPublishClase getControladorPublishClasePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Publicadores/", "ControladorPublishClasePort"), ControladorPublishClase.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTROLADORPUBLISHCLASESERVICE_EXCEPTION!= null) {
            throw CONTROLADORPUBLISHCLASESERVICE_EXCEPTION;
        }
        return CONTROLADORPUBLISHCLASESERVICE_WSDL_LOCATION;
    }

}
